### ISSUE TITLE
[SUGGESTION FOR WEBSITE] Multi-language support?

### ISSUE THREAD

**Issue by Blueberryy** [TTT-2/docs#11]
I would like to contribute a Russian translation for these docs

**Comment by saibotk** [comment]
Sure, awesome! 
I will give a look on how to do that properly with our tool and come back to you as soon as i found out.

**Comment by saibotk** [comment]
I looked into this and did not find a reasonable way to do this easily with mkdocs.
Also, it would be hard for us to verify the translation, and we may not be able to keep it up to date.

So we decided to not currently plan to support localization.
